# Generated by Django 3.1.4 on 2021-01-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='projector_availability',
            field=models.BooleanField(default=False, verbose_name='is_projector'),
        ),
    ]
